module.exports = [
    'Alice',
    'Medusa',
    'Sinbad',
    'King Arthur',
    'Dracula',
    'Sherlock Holmes',
    'Jekyll & Hyde',
    'Invisible Man',
    'Achilles',
    'Bloody Mary',
    'Sun Wukong',
    'Yennenga',
    'Bigfoot',
    'Robin Hood',
    'Beowulf',
    'Little Red Riding Hood',
    'InGen',
    'Raptors',
    'Dr. Sattler',
    'T. Rex',
    'Houdini',
    'The Genie',
    'Elektra',
    'Daredevil',
    'Bullseye',
    'Ghost Rider',
    'Luke Cage',
    'Moon Knight',
    'Cloak & Dagger',
    'Ms. Marvel',
    'Squirrel Girl'
]