module.exports = [
    'Alice',
    'Medusa',
    'Sinbad',
    'King Arthur',
    'Dracula',
    'Sherlock Holmes',
    'Jekyll & Hyde',
    'Invisible Man',
    'Achilles',
    'Bloody Mary',
    'Sun Wukong',
    'Yennenga',
    'Golden Bat',
    'Dr. Jill Trent',
    'Nikola Tesla',
    'Annie Christmas',
    'Bigfoot',
    'Robin Hood',
    'Beowulf',
    'Little Red Riding Hood',
    'InGen',
    'Raptors',
    'Dr. Sattler',
    'T. Rex',
    'Houdini',
    'The Genie',
    'Elektra',
    'Daredevil',
    'Bullseye',
    'Ghost Rider',
    'Luke Cage',
    'Moon Knight',
    'Cloak & Dagger',
    'Ms. Marvel',
    'Squirrel Girl',
    'Black Panther',
    'Winter Soldier',
    'Black Widow',
    'Spider-Man',
    'She-Hulk',
    'Doctor Strange',
    'Deadpool',
    'Bruce Lee',
    'Tomoe Gozen',
    'Oda Nobunaga',
    'Mothman',
    'Martian Invader'
]